#!/bin/sh

REPO_NAME=$(sed -n '/name/p' package.json | awk '{print $2}' | sed 's/"//g; s/,//g')
DIST_FOLDER="dist"

# Clean up dist folder
rm -Rf "$DIST_FOLDER/*"

# Run the build
npm run build

# Create a temp directory
mkdir "/tmp/$REPO_NAME"

# Copy all the build files to the temp directory
cp -R "$DIST_FOLDER/*" "/tmp/$REPO_NAME"

# Check out the gh-pages branch
git checkout gh-pages

# Remove all the files in the current branch
rm -Rf ./*

# Copy all the files from the temp directory
cp -R "/tmp/$REPO_NAME/*" ./

# Commit and push to gh-pages
git add .
git commit -m "Publishing demo for $(git describe --tags)"
git push origin gh-pages

# Checkout the master branch
git checkout master